pipelines:
  default:
    - step:
        name: PhizzleTestAutomation
        caches:
          - docker
        services:
          - docker
        script: 
          - export IMAGE_NAME=pharma/test-automation:latest
          - docker build -t $IMAGE_NAME .
          - docker tag $IMAGE_NAME pharma/test-automation:latest
          - pipe: atlassian/aws-ecr-push-image:1.0.2
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              IMAGE_NAME: pharma/test-automation
  custom:
      run-test-automation:
      - step:
          name: Run Test Automation
          script:
           # TODO: Yet to check aws cli is available or not.
           # Install if not available
            - aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
            - aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
            - eval $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            - docker run pharma/test-automation:latest